spring:
  application:
    name: ms-cn
    
  datasource:
    url: jdbc:mysql://localhost:3306/mscn?serverTimezone=UTC
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
